### ISSUE TITLE
US2_a-T1: Analyse the movielense database (create read me)

### ISSUE THREAD

**Issue by AlbaGarciaRomo** [ADS-2023-FR1/Agile-Data-Science-Project-FR1#7]
US2_a-T1: Analyse the movielense database. Discover what attributes are more important, perfom a PCA analysis, clustering or review the correlations. Create a document with this information, store it in the "Documentation" folder.

Estimated effort: 8

**Comment by ClaudiaValverde** [comment]
@AlbaGarciaRomo maybe we should store it in the Data folder

**Comment by AlbaGarciaRomo** [comment]
Okey @ClaudiaValverde whatever makes more sense :)
